# Generated by Django 2.1.15 on 2020-05-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('accountID', models.IntegerField()),
                ('addrressName', models.CharField(max_length=124)),
                ('aptnum', models.CharField(max_length=24)),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
                ('zipcode', models.IntegerField()),
                ('userAuthenticated', models.BooleanField()),
            ],
        ),
    ]
