# Generated by Django 2.1.15 on 2020-05-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bearbites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bearbites.Account')),
                ('customerID', models.IntegerField()),
                ('preference', models.CharField(max_length=150)),
                ('preferenceID', models.IntegerField()),
                ('allergyID', models.IntegerField()),
                ('allergy', models.CharField(max_length=128)),
            ],
            bases=('bearbites.account',),
        ),
    ]
