# Generated by Django 2.1.15 on 2020-05-14 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('delivery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.Delivery')),
                ('reviewID', models.IntegerField()),
                ('reviewType', models.CharField(max_length=128)),
                ('reviewRating', models.CharField(max_length=128)),
                ('reviewComment', models.CharField(max_length=128)),
            ],
            bases=('order.delivery',),
        ),
    ]
