# Generated by Django 2.1.15 on 2020-05-14 21:20

from django.db import migrations, models
import django.db.models.deletion
import order.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.Customer')),
                ('deliveryID', models.IntegerField()),
                ('restaurant', models.IntegerField()),
                ('deliveryAddressID', models.IntegerField()),
                ('deliveryDate', models.CharField(max_length=128)),
                ('deliveryTime', models.CharField(max_length=128)),
                ('deliveryInstructions', models.CharField(max_length=128)),
                ('tip', models.CharField(max_length=128)),
                ('status', models.CharField(max_length=128)),
            ],
            bases=('customer.customer',),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('delivery_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='order.Delivery')),
            ],
            bases=(order.models.CartItem, 'order.delivery'),
        ),
    ]
